modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (25 is current forge version)
license="All Rights Reserved"
[[mods]] #mandatory
modId="forbidden_arcanus" #mandatory
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Forbidden & Arcanus" #mandatory
credits="stal111, Xesar_Zk" #optional
authors="stal111, Xesar_Zk" #optional
# The description text for the mod (multi line!) (#mandatory)
description=''' '''